# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfbf707fa8e6ca0cdda349afe7fbd7cbf1a38b7b78b37b987073c8d770c2c8fbf6877169531936f0d415815521348a0004f5b4533ae191543ad478c59b31f179

test:
  secret_key_base: c76c28d436d1da77162a3f64943cd3e6294986b6a6c37fa6abb39dcf65a91e1de354ab150510903ec8f4ce58485548e5f9935cf728650336a864643f61997870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
